#!/bin/bash

# Triandos Chiro - Firebase Quick Start
# This script guides you through Firebase setup

echo "🔥 Firebase Setup for Triandos Chiro"
echo "===================================="
echo ""
echo "This will guide you through setting up Firebase in 5 minutes."
echo ""
echo "Prerequisites:"
echo "- Google account"
echo "- Access to https://console.firebase.google.com"
echo ""
echo "Let's get started! Follow these steps:"
echo ""
echo "📋 STEP 1: Create Firebase Project"
echo "===================================="
echo "1. Go to: https://console.firebase.google.com"
echo "2. Click 'Create a new project'"
echo "3. Project name: triandos-chiro"
echo "4. Select region: United States"
echo "5. Click 'Create project'"
echo ""
read -p "Press ENTER once you've created the project..."
echo ""

echo "📋 STEP 2: Add iOS App"
echo "====================="
echo "1. In Firebase console, click the iOS icon"
echo "2. Bundle ID: com.triandoschiro.app"
echo "3. App nickname: Triandos Chiro"
echo "4. Click 'Register app'"
echo "5. Click 'Download GoogleService-Info.plist'"
echo ""
read -p "Press ENTER after downloading the plist file..."
echo ""

echo "📋 STEP 3: Add plist to Project"
echo "================================"
echo "1. Open Xcode"
echo "2. Go to: ios/TriandosChiro.xcworkspace"
echo "3. Right-click 'TriandosChiro' project"
echo "4. Select 'Add Files to TriandosChiro'"
echo "5. Choose the GoogleService-Info.plist file you downloaded"
echo "6. Make sure 'Copy items if needed' is checked"
echo "7. Make sure 'TriandosChiro' target is selected"
echo "8. Click 'Add'"
echo ""
read -p "Press ENTER once you've added the plist to Xcode..."
echo ""

echo "📋 STEP 4: Enable Authentication"
echo "================================="
echo "1. Go back to Firebase console"
echo "2. Click 'Authentication' in the left menu"
echo "3. Click 'Get started' or 'Sign-in method'"
echo "4. Click 'Email/Password'"
echo "5. Toggle 'Enable'"
echo "6. Click 'Save'"
echo ""
read -p "Press ENTER after enabling Email/Password auth..."
echo ""

echo "📋 STEP 5: Create Firestore Database"
echo "===================================="
echo "1. In Firebase console, click 'Firestore Database'"
echo "2. Click 'Create database'"
echo "3. Start in 'Test mode' (for development)"
echo "4. Region: us-central1"
echo "5. Click 'Create database'"
echo ""
read -p "Press ENTER once the database is created..."
echo ""

echo "📋 STEP 6: Update Firestore Security Rules"
echo "==========================================="
echo "1. In Firestore, go to the 'Rules' tab"
echo "2. Copy the rules from: FIREBASE_SETUP.md (see the rules section)"
echo "3. Paste into the rules editor"
echo "4. Click 'Publish'"
echo ""
read -p "Press ENTER after publishing the security rules..."
echo ""

echo ""
echo "✅ Firebase is all set up!"
echo ""
echo "Next steps:"
echo "1. npm install"
echo "2. cd ios && pod install --repo-update && cd .."
echo "3. npm run ios (test on simulator)"
echo "4. git push origin main (triggers TestFlight build)"
echo ""
