require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'TriandosChiro' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :arch => "arm64"
  )

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'TriandosChiroTests' do
    inherit! :search_paths
  end
end
